name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main  # Cambiado a 'main' como la rama principal para tus despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Actualizado a la versión estable v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to S3
        run: |
          # Apuntamos el sync a '.' porque tu web estática está en la raíz de tu repo (no en /public)
          aws s3 sync . s3://${{ vars.S3_BUCKET }} --delete --exclude ".git/*" --exclude ".github/*" --exclude "static/invitaciones/*" --exclude "*.old*" --exclude "v2/*"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIBUTION_ID }} --paths "/*"